package main;

import java.util.Arrays;
import java.util.List;
import main.Item;
import test.ItemRepositoryTestImpl;
import test.SalesPromotionRepositoryTestImpl;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
    	StringBuffer jieguo = new StringBuffer();
    	String a="============= 订餐明细 =============\n" ;
    	jieguo.append(a);
        ItemRepositoryTestImpl itemRepository = new ItemRepositoryTestImpl();
    	SalesPromotionRepositoryTestImpl salesPromotionRepository = new SalesPromotionRepositoryTestImpl();
    	
		List<Item> it=itemRepository.findAll();
    	
		List<SalesPromotion> sa=salesPromotionRepository.findAll();
		//计算哪个优惠
    	double wuzhe=0;//五折优惠
		double wuzhezong;//五折总价
    	double manjianzong=0;//满减总价
    	double putongzong=0;//普通总价
    	String wuzhename="";//优惠名称
    	String manjianname = "";
    	int flag=1;
    	for (String s : inputs) {
    		s=s.replace(" ", "");
    		String[] aa=s.split("x");
    		for (Item i : it) {
        		if(aa[0].equals(i.getId())){//找出价格
        			int intaa =Integer.parseInt(aa[1]);//找出数量
        			a=i.getName()+"x"+aa[1]+"="+i.getPrice()*intaa+"元\n";
        			jieguo.append(a);
        			putongzong=putongzong+i.getPrice()*intaa;//算出总价
        			if(aa[0].equals("ITEM0001")||aa[0].equals("ITEM0022")){
        				wuzhe =wuzhe+(i.getPrice()*0.5*intaa);	//算出优惠	
        			}
        		}
    			
    		}
		}
    	for (SalesPromotion salPro : sa) {
    		if(salPro.getType().equals("BUY_30_SAVE_6_YUAN")) manjianname=salPro.getDisplayName();
    		else wuzhename=salPro.getDisplayName();
		}
    	//五折
    	if(wuzhe==0&&putongzong<30){
    		a= "-----------------------------------\n" +
                    "总计："+putongzong+"元\n"+
                    "===================================";
    	}else{
	    	wuzhezong=putongzong-wuzhe;
	    	if(putongzong>=30) manjianzong=putongzong-6;
	    	if(wuzhezong>=manjianzong){//满减少，用满减		
	    		a= "-----------------------------------\n" +
	                    "使用优惠:\n" +manjianname+
	                    "，省6元\n" +
	                    "-----------------------------------\n" +
	                    "总计："+manjianzong+"元\n"+
	                    "===================================";
	    	}else{	
	    		a=  "-----------------------------------\n" +
	                    "使用优惠:\n" +wuzhename+
	                    "(黄焖鸡，凉皮)，省" +wuzhe+"元\n"+
	                    "总计："+wuzhezong+"元\n" +
	                    "===================================" ; 		
	    	}
    	}
    	jieguo.append(a);
        return jieguo.toString();
    }
}
